name: Deploy to VDS Server (Native)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 1. Создание промежуточной папки если её нет
          mkdir -p /home/tournament-admin/tournaments-temp
          
          # 2. Push в промежуточную папку (исправлено - исключаем системные директории)
          rm -rf /home/tournament-admin/tournaments-temp/*
          
          # Копирование только файлов проекта (исключая системные директории)
          find $GITHUB_WORKSPACE -maxdepth 1 -type f -exec cp {} /home/tournament-admin/tournaments-temp/ \;
          find $GITHUB_WORKSPACE -maxdepth 1 -type d -not -path "$GITHUB_WORKSPACE" -not -name ".*" -not -name "proc" -not -name "sys" -not -name "dev" -not -name "boot" -not -name "etc" -not -name "home" -not -name "lib" -not -name "lib64" -not -name "opt" -not -name "root" -not -name "run" -not -name "sbin" -not -name "snap" -not -name "srv" -not -name "tmp" -not -name "usr" -not -name "var" -exec cp -r {} /home/tournament-admin/tournaments-temp/ \;
          
          # 3. Проверка пуша
          echo "Проверка файлов в промежуточной папке:"
          ls -la /home/tournament-admin/tournaments-temp/
          echo "Проверка размера промежуточной папки:"
          du -sh /home/tournament-admin/tournaments-temp/
          
          # 4. Остановка приложения
          sudo systemctl stop tournament-app || true
          echo "Приложение остановлено"
          
          # 4.5. Сохранение копии рабочей папки в backup (только 1 копия)
          echo "Создание backup рабочей папки..."
          mkdir -p /home/tournament-admin/backups
          
          # Удаление старого backup (если есть)
          rm -rf /home/tournament-admin/backups/tournaments-backup
          
          # Создание нового backup
          cp -r /home/tournament-admin/tournaments /home/tournament-admin/backups/tournaments-backup
          echo "Backup создан: /home/tournament-admin/backups/tournaments-backup"
          echo "Размер backup: $(du -sh /home/tournament-admin/backups/tournaments-backup)"
          
          # 5. Копирование в рабочую папку
          rm -rf /home/tournament-admin/tournaments/*
          cp -r /home/tournament-admin/tournaments-temp/* /home/tournament-admin/tournaments/
          echo "Файлы скопированы в рабочую папку"
          
          # 6. Активация окружения и установка зависимостей
          cd /home/tournament-admin/tournaments
          source venv/bin/activate
          pip install -r requirements.txt
          echo "Зависимости обновлены"
          
          # 7. Запуск приложения
          sudo systemctl start tournament-app
          echo "Приложение запущено"
          
          # 8. Проверка статуса
          sleep 5
          sudo systemctl status tournament-app --no-pager
          
          # 9. Проверка работы
          curl -I http://127.0.0.1:5000 || echo "Локальная проверка не удалась"
          
          echo "Deployment completed successfully!"
        script_stop: true
        envs: GITHUB_SHA