name: Deploy to VDS Server (Native)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/tournament-admin/tournaments
          # Копируем код напрямую из GitHub Actions
          rm -rf /home/tournament-admin/tournaments/*
          cp -r /github/workspace/* /home/tournament-admin/tournaments/
          # Останавливаем приложение
          sudo systemctl stop tournament-app || true
          # Активируем виртуальное окружение и обновляем зависимости
          source venv/bin/activate
          pip install -r requirements.txt
          # Запускаем приложение
          sudo systemctl start tournament-app
          # Проверяем статус
          sleep 5
          sudo systemctl status tournament-app --no-pager
          echo "Deployment completed successfully!"
        script_stop: true
        envs: GITHUB_SHA